### ISSUE TITLE
task prompt function type does not contain previous prompt

### ISSUE THREAD

**Issue by muuvmuuv** [cenk1cenk2/listr2#162]
I am trying to do a row of prompts and want one prompt to be skipped or of type text. The simplest solution for this is to use an if-statement with a previous prompt's response value, but the ctx does not contain the previous just the current prompt.

```js
      ctx.version = await task.prompt([
        {
          type: 'select',
          name: 'version',
          message: 'New version',
          choices
        },
        {
          // prev contains only current prompt not from select version
          type: (prev) => (prev == 'custom' ? 'text' : null),
          name: 'version',
          message: 'Version',
          validate: validator,
        },
      ])
```

> https://github.com/terkelg/prompts#-prompt-objects

**Comment by cenk1cenk2** [comment]
Input module uses [enquirer](https://www.npmjs.com/package/enquirer), which you can utilize its own options through seeing examples [here](https://github.com/cenk1cenk2/listr2#get-user-input), albeit not all the types might be correct for it since I had to rewrote them to utilize it. 

If you want to utilize another package you have to utilize the [stdout passthrough](https://github.com/cenk1cenk2/listr2#passing-the-output-through-as-a-stream), although the example is for INK it should be very similar and I have checked that this module also can use `{ stdout }` option to change the stdout which will pass through the internal stream through Listr since log-update takes full control of the `process.stdout`. You can set `task.prompt = true` and return any error as `task.prompt = new PromptError('some string')` to achieve a similar output style to the default.

You can see the inner workings of `task.prompt` [here](https://github.com/cenk1cenk2/listr2/blob/5ecfb4db4112e7bad61ccb36c1b8938ef2412dfc/src/lib/task-wrapper.ts#L85).

The prompts are intended to be single seperate tasks, since the output data control of them is a bit tricky with the given code-base.

**Comment by muuvmuuv** [comment]
I also noticed that it uses enquirer, thought I read prompts somewhere. Fixed that and split them into separate tasks which worked. No need to utilize another prompt package. Looking forwards for connected multi prompts in the future.

**Comment by cenk1cenk2** [comment]
Hmm. I am sorry if i understand your question wrong. But it should in theory support all the functionality of enquirer eventhough the types might be wrong. So if using typescript you might need to add ts-ignore and i can fix the types on an open issue. I can also add this package later on and create a flag to select the prompt package since it also seems cool.

Hope you have fun with your project.
