### ISSUE TITLE
[Regression] Promise rejections are handled, but task is removed from list

### ISSUE THREAD

**Issue by chet-manley** [cenk1cenk2/listr2#163]
# Current Behavior

In Listr, rejected promises and thrown errors are displayed in the list, but they remain uncaught. Listr2 appears to have fixed the issue by handling errors; however, tasks that return a rejected promise are removed from the task list, and thrown errors overwrite the task title.
[This example on Repl.it](https://repl.it/repls/CanineNimbleAssociate#index.js) demonstrates the described behavior.

## Expected Behavior

- Tasks are never removed from list, mimicking the behavior of Listr.
- Error message is displayed as task output, mimicking the behavior of Listr.
- Rejected promises display error messages or strings as task output.

## Proposed Behavior

Having task titles overwritten by default is a poor design choice from a UX perspective, be it from errors or skipping. 

- Add an `overwriteTitles` key to `rendererOptions`, that controls this behavior. 
- Error and skip messages should be displayed _as output_ by default. 
  - This will not be a breaking change, as the _current_ behavior is already a breaking change from the expected output. 
- Rejected promises display error messages or strings as task output.

**Comment by cenk1cenk2** [comment]
There is a flag like collapse skips. Maybe a collapse errors can replicate the behaviour?

**Comment by chet-manley** [comment]
After dealing with the disappearing tasks issue, I would agree that `collapseErrors` is useful functionality, and a first step in the right direction. However, the proposed functionality of `overwriteTitles` remains imperative, and should be placed in the `rendererOptions` scope. For _every single task I need to skip_, I am currently required to include the following code block just to prevent my titles from being overwritten, regardless of collapse settings:

```javascript
if (!repository) {
  return task.skip(
    task.options.rendererOptions.collapseSkips
      ? task.title
      : 'missing repository URL'
  )
}
```
I don't _ever_ want my titles to be overwritten, under any circumstance; so even if it is a single-line task, I have to place that entire block inside the task (instead of just using the provided skip property). I do not wish to insert a similarly large block for every single task, just in case it errors. It is an anti-pattern. I would go so far as to say that there is a _strong_ argument to be made (from a UX perspective) that the option should be `false` by default, but just having the option available is a 100% improvement. Also, the current functionality breaks the expected output of the original Listr.

**Comment by cenk1cenk2** [comment]
I am on mobile and I can not try it at the moment but if you use collapseSkips: false and send a empty string as skip message I think that it would not overwrite the current message but just append [skipped] as suffix to the title. But i can fix that by making the skip message optional. Therefore eventhough the overwriting titles is the default it would just be an opt-in feature. Maybe can be the same with throwing an error as well.

**Comment by cenk1cenk2** [comment]
Similar to `collapseSkips`, I have more options added like it where you can:
- Disable adding `[SKIPPED]` to skipped tasks with `suffixSkips` in the default renderer.
- Disable showing skip message with `showSkipMessage` where the task title will be shown even though skip has a message.
- If you send an empty `task.skip()`, it will use the task title.
- Disable showing the error message with `showErrorMessage` where the task title will be shown even though there is an error message.
- A `collapseErrors` option which is similar to `collapseSkips` and it will show the task title untouched and error message as output.

This is more than the changes that I have hoped for and the ETA will be longer since I want to test all the functionality first.

```typescript
public static rendererOptions: {
    // indentation per level
    indentation?: number
    // clear output when task finishes
    clearOutput?: boolean
    // show subtasks
    showSubtasks?: boolean
    // collapse subtasks after finish
    collapse?: boolean
    // collapse skip messages in to single message in task title
    collapseSkips?: boolean
    // show skip messages or show the original title of the task when in collapseSkips Mode
    showSkipMessage?: boolean
    // suffix skip messages with [SKIPPED] when in collapseSkips mode
    suffixSkips?: boolean
    // collapse error messages in to single message in task title
    collapseErrors?: boolean
    // shows the thrown error message or show the original title of the task when in collapseErrors mode
    showErrorMessage?: boolean
    // only update via renderhook
    lazy?: boolean
    // show duration for all tasks overwrites per task options
    showTimer?: boolean
  } = {
    indentation: 2,
    clearOutput: false,
    showSubtasks: true,
    collapse: true,
    collapseSkips: true,
    showSkipMessage: true,
    suffixSkips: true,
    collapseErrors: true,
    showErrorMessage: true,
    lazy: false,
    showTimer: false
  }
```

I wanted to change the final render of the tasks from `log-update` to `process.stdout.write` since `log-update` can only control the seen height of the terminal due to the limitation of terminals. The long tasks can not be scrolled properly after the final render and it is mangled a bit.

So combining it with this it will be a major release since it might break some tests.

**Comment by cenk1cenk2** [comment]
Can you please test this out on 3.0.0-beta.1 by `listr2@beta` and inform me if it works better for you.

**Comment by chet-manley** [comment]
> I wanted to change the final render of the tasks from `log-update` to `process.stdout.write` since `log-update` can only control the seen height of the terminal due to the limitation of terminals. The long tasks can not be scrolled properly after the final render and it is mangled a bit.

I was going to raise an issue for that. Glad it is already being addressed. 

> Can you please test this out on 3.0.0-beta.1 by listr2@beta and inform me if it works better for you.

I did some testing with the new beta, and it does appear to fix the original issue regarding errored tasks being removed from the list, as well as the other concerns I raised. However, my testing revealed some new/different issues. My [Repl.it](https://repl.it/repls/CanineNimbleAssociate#index.js) has been updated to demonstrate the following issues:

- If a nested task throws an error, `exitOnError` is `true`, and `collapseErrors` is `false`, the parent task also outputs the error message (as-if it were a normal task).
-  If `exitOnError` is `false`, the above does not occur.
- Rejected promises output the task title instead of error message/reject value, regardless of options. 

I would recommend renaming `showErrorMessage` and `showSkipMessage`, as these names don't exactly describe what is actually being accomplished with them. E.g., if both `collapseErrors` and `showErrorMessage` are `false`, the error message is still displayed as task output. While this is the desired behavior, one would expect the error message to be suppressed by the `showErrorMessage` option being set to `false`. I would recommend something closer to `collapseErrorsOverwriteTitle`, or just something more descriptive.

Thanks for the quick response. As soon as this is out of beta, it will be going into my current project.

**Comment by cenk1cenk2** [comment]
Yeah that is true showErrorMessage or showSkipMessage with collapseErrors collapseSkips is bit a counter intuative I have not thought about it since I did not intend them to be used together. I will adress that.

I can live the name showErrorMessages and skipMessages but make them more intuatuve to disable the output of the errors or skips compeletely which will make them more true to their name.

I will also adress the other issue with subtask errors since I have moved the handling of that to renderer recently.

**Comment by cenk1cenk2** [comment]
Thanks again for this through testing and bringing new ideas to the table it is much appriciated.

**Comment by cenk1cenk2** [comment]
Okay I forked your replicate it with [this](https://repl.it/repls/UprightCostlyFormula#new.ts)

It does not like uncatched errors with `Promise.reject` somehow. Other async tasks that fail will show their messages correctly but somehow with the Promise constructor, this is not possible.

```typescript
/** Promise.reject tests */
const listr2PromiseRejectNoCollapse = new Listr2([
  {
    title: 'TITLE Promise Reject',
    task: (_) => Promise.reject('error message').catch((e) => { throw new Error(e) }),
    options: { }
  }
], {
  exitOnError: false,
  rendererOptions: {
    collapseErrors: false
  }
})
```

I will push a fast fix for the rest since I have limited time today and do not want to block your flow.

**Comment by cenk1cenk2** [comment]
Oh it is my bad ofc. If you promise.reject with new Error it should be fine.

**Comment by chet-manley** [comment]
Since a rejected Promise can reasonably be assumed to always be a failure condition, and since a rejection can return any value, I think the most graceful failure method would be to check the return value. If it is a String or an object containing a `message` property, output that as the error message (rejecting with just a string, while not best practice, is both valid and not entirely uncommon). Otherwise, mark as failed and display no message. Anyone not using the built-in Promise factory in 2020 can be expected to catch and re-throw their own errors. That is the most elegant and feature-complete solution I can come up with off the top of my head, but expecting users to catch and throw their own rejections when using proper Promises seems like the wrong path overall. Doesn't affect _my_ project implementation any, but just my $0.02.
