### ISSUE TITLE
Option to Disable Truncation / Empty Line removal?

### ISSUE THREAD

**Issue by karlhorky** [cenk1cenk2/listr2#260]
Hi there! 👋

First of all, thanks for your contribution of `listr2` to the community! This is a great library, and saves a bunch of boilerplate!

I am a bit confused with listr2's behavior of truncating and removing empty lines in my errors. The content and the formatting that I'm writing in the errors is important, and I would like it to stay the same.

See the error in the source code and the formatting in the terminal. The first line of the error is truncated and the empty line is removed:

![Screen Shot 2021-01-16 at 16 54 57](https://user-images.githubusercontent.com/1935696/104816519-07e97100-581c-11eb-8841-51a96cce5008.png)

Here are our options:

```js
{
  exitOnError: false,
  rendererOptions: { collapseErrors: false },
  concurrent: 5,
}
```

It seems like this could also be a default for `listr2`, but maybe there's a reason why that's not a good idea.

cc @Josehower

**Comment by cenk1cenk2** [comment]
Hello Karl,

I will have some time to implement the option tomorrow with the other issue I also have in hand. But generally, the main reason is the truncation of strings is the default is since log-update the library this module and the original depends upon can show some weird behavior if you exceed the terminal height or width. But of course, I can leave an option to do that if you wish.

The other one where it removes the spaces is only because is mostly because of my personal preferences. As you can see in [here](https://github.com/cenk1cenk2/servicecmd), when I feed something like the output of a process, the application might log out empty lines, so I do not want it to delete the output line that is present. But again I can add an option to the renderer to remove that behavior.

Hopefully, I will find tomorrow sometime for self-coding, therefore address these issues. Till then have fun.

**Comment by karlhorky** [comment]
Oh wow, thanks! That sounds great.

May I suggest switching `cli-truncate` to [`wrap-ansi`](https://www.npmjs.com/package/wrap-ansi) to word wrap the strings instead of truncating them? Would this be ok for you as a default?

This is my workaround for now, using `wrap-ansi`:

```js
throw Error(
  wrapAnsi(
    `Super long line with tons of content. The continuation of this super long line with tons of content. And some more. Super long line with tons of content. The continuation of this super long line with tons of content. And some more.`,
    process.stdout.columns - 2
  )
);
```

Not sure why I need to subtract `2` from the `process.stdout.columns`, but if I don't have that, then it still truncates... 🤔

**Comment by cenk1cenk2** [comment]
Yeah because it is intended by a number depending on which level of subtask it is for the first level it would be 2. I was thinking about the same because with truncation gone we will definitely need something like this to not break log-update.

**Comment by karlhorky** [comment]
Ah, one caveat to switching to `wrap-ansi` may be long, unbreakable lines like a URL.

**Comment by cenk1cenk2** [comment]
I think I would add my own function for it since it is pretty basic, but I am not sure to include it as a default since it is so little change that will introduce breaking changes and may require the update on scripts that require this library. But it would definitely be a good option for the renderer. Maybe what I will try is not break the words, but it will get a little more complicated while processing fast output, and not sure if not look that good in the result some lines being more empty than others.

**Comment by cenk1cenk2** [comment]
Oh but I think for longer links than available terminal space it wouldn't work anyhow.

**Comment by karlhorky** [comment]
Yeah, check my comment to the `{ hard: true }` option above.

**Comment by karlhorky** [comment]
> I am not sure to include it as a default since it is so little change that will introduce breaking changes

Right yeah, after consideration it seems setting as default would be risky.

Maybe an option as such:

```
type Options = {
  // default 'truncate'
  formatLongLines:
    'truncate' |
    'hardWrap' |
    false
}
```

**Comment by cenk1cenk2** [comment]
Yeah definitely agree with this solution, that would be something easy and intuitive to implement. I know setting default options for a library is hell every time. That's why I did add this `manager` maybe it would be useful for you too.

You can use it along the where you return this manager from a factory or so.
https://github.com/cenk1cenk2/boilerplate-oclif/blob/38851f1e5795afe7408bef464de40043e040fe9c/packages/common/src/lib/base/base.command.ts#L49

**Comment by cenk1cenk2** [comment]
I have given it a try but it seems it requires a bit of refactoring so closing the other issue today, I will check this one some other time, if it is convenient for you.

**Comment by karlhorky** [comment]
Yeah, no problem - take your time.

I have workarounds for both for now:

- lines being truncated: [the `wrap-ansi` workaround above](https://github.com/cenk1cenk2/listr2/issues/260#issuecomment-761598464)
- empty lines being stripped: see below

I use the [empty Braille unicode character](https://www.compart.com/en/unicode/U+2800) to create an empty line:

```js
// https://www.compart.com/en/unicode/U+2800
const emptyBrailleCharacter = '‎';

throw Error(
  `Here's a first line. Next comes an empty line:
    ${emptyBrailleCharacter}
    Here's a third line`
);
```

**Comment by cenk1cenk2** [comment]
Hello @karlhorky,

This has been released on the @beta channel. It required some idiomatic checks since there was per-line indentation and did take longer than expected, without breaking anything essential on tests.

Both functions are implemented, please give it a try and tell me what you think.

I will update the documentation this week then merge it to the mainstream branch.

Have a good day.

**Comment by karlhorky** [comment]
Ah nice, thanks! I'll take a look at whether it works in my project in the next few days.

I noticed that [you have `wrap` and `wordWrap` options](https://github.com/cenk1cenk2/listr2/pull/263/files#diff-2f325cadd635547ef73e04d65671911b5ff797cdef1876c94d6bd0de6a12cdeeR461-R474), but they are actually functionally doing the same thing, because [`wordWrap` defaults to `true` in `wrap-ansi`](https://www.npmjs.com/package/wrap-ansi#wordwrap).

So maybe either an option for non-hard wrapping (eg. `hardWrap` / `softWrap`), or just a single `wrap` option...? (which always does hard wrapping)

**Comment by cenk1cenk2** [comment]
I am not sure we can do soft wrapping due to `log-update` because it already handles that but the indentation would be wrong using `log-update` wrapping. 

Then I will remove the hard wrap, because yeah it seemed to my eyes they were both doing the same thing as well while testing, but since we talked about it, I decided to keep it.

Please inform me whether it works for you whenever you get the chance to use it.

Thank you.

**Comment by karlhorky** [comment]
Ok great, so to be clear, there will just be a single wrap option `formatOutput: 'wrap'`, is that correct?

**Comment by cenk1cenk2** [comment]
Yes, that is exactly true.

**Comment by karlhorky** [comment]
Nice, just tested `formatOutput: 'wrap'` and it seems to be working:

<img width="484" alt="Screen Shot 2021-01-20 at 17 47 26" src="https://user-images.githubusercontent.com/1935696/105207267-99702000-5b47-11eb-8982-3b6d9b32b80b.png">

Thumbs-up from me on release! 🚀

**Comment by cenk1cenk2** [comment]
That is great thank you for your feedback. I will update the readme and release it.

**Comment by karlhorky** [comment]
Awesome, thanks! Upgraded in https://github.com/upleveled/preflight/commit/f39d3850591459166cf3de797d370a97e3132e2e 🙌

**Comment by cenk1cenk2** [comment]
Great, glad it fixed your problem.
