### ISSUE TITLE
How to output stream progress

### ISSUE THREAD

**Issue by vladshcherbin** [cenk1cenk2/listr2#302]
Hey 👋 

I've got a download stream with `on('progress')` event:

```js
{
  title: 'Download task',
  task: () => {
    const stream = downloadStream(videoUrl)
      .on('progress', ({ num }, totalSegments, bytes) => {
        // send to listr
      })

    stream.pipe(fs.createWriteStream('videofile.mp4'))

    return stream
  }
}
```

If I use above code, chunks of downloaded data will be shown in console. I'd love to show message from `progress` event.

I don't have enough knowledge with streams, I've tried some ideas but didn't succeed. Is it somehow possible?

**Comment by cenk1cenk2** [comment]
Yes, this should be possible. 

Even though I can not try it out at the current moment it should go something like this:
- Convert the stream into a promise by wrapping it.
- Pipe the output to `task.output`.
- If you want to use a progress bar, which I did not implement in yet since it needs some other work to do so, choose a one that supports `stdout` variable so you can redirect the `stdout` of the progress bar to `task.stdout()`

```typescript
{
  title: 'Download task',
  task: (_, task) =>  new Promise((resolve, reject) => { 
       const stream = downloadStream(videoUrl)
       stream.on('end',  () => resolve(null))
         .on('error',  (err) => reject(err))
         .on('progress', ({ num }, totalSegments, bytes) => {
         
         task.output = `something something with these things`
      })
       stream.pipe(fs.createWriteStream('videofile.mp4'))
   }
)
```

Can you try this kind of approach and inform me how it goes? The stream output is like more intended to passthrough `stdout` of a shell command like [here](https://github.com/cenk1cenk2/servicecmd/blob/46e2e2a8de30edb1f33e6d5aa2eab20d82e1c210/packages/cli/src/commands/docker/index.ts#L286). 

I will, later on, try to add an embedded progress bar with later iterations that you can update, but it is a low priority at the moment.

**Comment by vladshcherbin** [comment]
Yep, this works great for me. I've tried to create another stream, push progress there and return in `task` 🤦 

Converting it to promise solves my task as I wanted to change title (add progress and downloaded bytes to it) with `task.title`.

Thank you a lot! ❤️
