### ISSUE TITLE
How to use it with Ink

### ISSUE THREAD

**Issue by vinodhum** [cenk1cenk2/listr2#31]
How can I use this with  [Ink](https://github.com/vadimdemedes/ink#readme) ?
and when running on git bash, spinner is showing only line, it not showing rotating dots link in demo, and symbols are very small, is there a way to customize it ?

**Comment by cenk1cenk2** [comment]
By default it fallback to more uglier symbols for Windows. Thats the nature of utilized packages. Until Windows Terminal or some other customizable terminals like ConEmu or Hyper.js, it was not reliable to show symbols in Windows Terminals.

For using it with this with Ink since which also utilizes a terminal clean up renderer you have to pass it through this renderer in something like prompt function of https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts . If stdout can be set in Ink. I can expose a function to utilize it.

Spinner: https://www.npmjs.com/package/elegant-spinner
Symbols:
Symbols:
https://www.npmjs.com/package/figures

**Comment by cenk1cenk2** [comment]
I have given this a thorough try. Since I wanted to pass Ink as an output of the task. 

The renderer utilizes an interval to refresh the tasks, and this INK or any other library that uses stdout utilizes ANSI escape sequences to clear out the screen, these escape sequences might be outputted more than one time depending on their rate of refresh compared to the render interval. This causes the to clear the output unexpectedly. 

There are two ways to obtain this functionality:
1) The first one was to catch these ANSI sequences then process them in a sandbox variable and clear out the ANSI sequences, as it was done for the prompt. But prompt was a specific use-case and I did not have to implement a lot to render it properly. So this is a lot of work. Unless I find a module that can sandbox these ANSI sequences into a given variable and clear them out after processing it as told.
2) The second alternative is to change the render method to an event-based system instead of interval. This will require some critical structural changes to function properly albeit it is a more effective way to render stuff reactively.

So although I will give this another try since I already wanted to expose STDOUT for other functionality as output, it may take longer than expected.

I will always use the icons in the demo from now on, even though some Windows terminals may not support it.

**Comment by cenk1cenk2** [comment]
Please give this a try with the latest beta channel which resides [here](https://github.com/cenk1cenk2/listr2/tree/beta).

 The section you are interested about passing the stdout through listr is [here](https://github.com/cenk1cenk2/listr2/tree/beta#passing-the-output-through-as-a-stream). It is by no means perfect, but it was the least I can do without creating a sandboxed terminal in the output section. It is what you call quick and dirty, albeit it may require some tweaking because it doesn't set the rows and columns properly.

Please open up a new issue for further. Looking forward for your feedback.

```bash
npm i listr2@beta
yarn add listr2@beta
```
