### ISSUE TITLE
edge case: last log line

### ISSUE THREAD

**Issue by metasean** [cenk1cenk2/listr2#310]
First run the following exactly as is, then uncomment line 14 and re-run it:
```ts
const { Listr } = require('Listr2');

const tasks = new Listr([
  {
    title: 'Demo of edge case',
    task: async (ctx, task) => {
      console.log('I thought I was losing my mind.')
      console.log('Turns out that I\'m not losing it (yet), it\'s just an edge case.')
      console.log('Specifically, when the task includes:')
      console.log('options: {\n\tpersistentOutput: true\n}')
      console.log('and the Listr options include:')
      console.log('{\n\trendererOptions: { collapse: false }\n}')
      console.error('Then the last displayable line of either a console.log or console.error (and presumably, their other variations, e.g. console.warn, console.table, etc) is overwritten')
      // console.log('unless the last line ends with a \\n\n')
    },
    options: {
      persistentOutput: true
    }
  },
], {
  rendererOptions: { collapse: false }
});

tasks.run()
  .then(() => { })
  .catch(() => { });
 ```

**Comment by metasean** [comment]
Also, if I ever find myself in Vienna or you find yourself in the Salt Lake City, UT area, I definitely owe you a drink!

**Comment by cenk1cenk2** [comment]
Hello @metasean ,
This is known since log-update package breaks with anything interfering. I am working on a better solution with another library from keindev, which you can track [here](https://github.com/cenk1cenk2/listr2/issues/296). There is a branch in the repo as well, but yet I have to fix the aforementioned updating render which will render the lines static. The library by keindev hooks the process.stdout and then outputs everything after. If you want to use console.log s you can use the silent renderer for now but unfortunetly this is a limitation at the moment.

**Comment by cenk1cenk2** [comment]
I am closing this issue in favor of #296.
