### ISSUE TITLE
task-level exitOnError option

### ISSUE THREAD

**Issue by sarink** [cenk1cenk2/listr2#339]
I have some tasks in my list that are ok to fail, and some that are not. I thought I could pass the `exitOnError: false` option to a task, but it appears that that option can only be passed while calling `run`.

This doesn't work, when encountering the error list exits
```
  const listr = new Listr(
    [
      {
        title: 'Allow fail',
        task: () => {
          throw new Error();
        },
        options: { exitOnError: false },
      },
    ];
```

As a workaround
```
  const listr = new Listr(
    [
      {
        title: 'Allow fail',
        task: (ctx, task) => {
          return task.newListr(
            [
              {
                task: () => {
                  throw new Error();
                },
              },
            ],
            { exitOnError: false }
          );
        },
      },
    ]
```
this works as desired, but is inconvenient. Is there another way?

**Comment by cenk1cenk2** [comment]
Yeah it is mostly on the subtask level so wherever a Listr class is defined. The options in the task itself is the per task renderer options and do not change the behavior. But we can add a key to task itself like skip or enabled called exitOnError and make this more convient on per task level. You can also catch the error thats what I do mostly but it will show itself as successful with a tick then. So the best bet is to add a key to the task definition. Sorry for janky answer since I am on mobile.

**Comment by cenk1cenk2** [comment]
Sorry for taking this long, but it is now implemented in.
