### ISSUE TITLE
Capture `stdin` with `execa` to run interactive suprocesses

### ISSUE THREAD

**Issue by mikenikles** [cenk1cenk2/listr2#368]
Hi,

First of all, thanks for maintaining this project 🙏 !

As part of one of my tasks, I'd like to execute `npm init svelte@next -y`. The challenge I run into is that the `npm init` script is interactive and displays a number of prompts.

My task currently looks like this:

```ts
const initWebApp = (ctx: Ctx, task: WebstoneTask) => {
  ctx.webAppDir = `${ctx.appDir}/services/web`;

  fs.removeSync(`${ctx.webAppDir}/.keep`);

  const svelteSubprocess = execa("npm init -y svelte@next", {
    cwd: ctx.webAppDir,
    shell: true,
    stdio: "inherit",
  });
  // svelteSubprocess.stdout.pipe(task.stdout())
  return svelteSubprocess;
};
```

If I comment out the line above the `return` statement, the task fails with `TypeError: Cannot read property pipe of null`, which makes sense. The subprocess then executes, but any tasks defined afterwards fail, which also makes sense.

Is it possible to capture a user's input to that subprocess and once the subprocess completed, continue with the next task in my list?

**Comment by cenk1cenk2** [comment]
Hmm, I am not sure I understand one hundred percent. So you want to capture the stdout and display it as output as well as take control of stdin and pass in tbe answers right?

**Comment by cenk1cenk2** [comment]
The way I usually pipe it through is like [here](https://github.com/cenk1cenk2/servicecmd/blob/9d993a9171278745396151edc974cb69640a4c85/packages/cli/src/commands/docker/index.ts#L307) as instance is defined in [here](https://github.com/cenk1cenk2/servicecmd/blob/9d993a9171278745396151edc974cb69640a4c85/packages/cli/src/commands/docker/index.ts#L278). There is also the case you can return the stream itself [as in examples](https://github.com/cenk1cenk2/listr2/blob/fdf112ae05a46bd8b321379ce8aca0799c677e1f/examples/stream.example.ts#L26). But I mostly use the other way around to have more control over it.

The stdin part may be tricky I guess you have to create another readable stream.
```typescript
// have to create some readable stream with
rl.on('line', (input) => {
  passToStream(input)
});
}
 const svelteSubprocess = execa("npm init svelte@next -y", {
    cwd: ctx.webAppDir,
    shell: true,
    stdin: theReadableSystemItself,
  });
```
Sorry for the not complete answer since I am on mobile.

**Comment by mikenikles** [comment]
Hey Cenk, thank you so much for your feedback. I experimented with that a bit in my project's pull request (see reference above this comment). I left instructions in the PR if you want to use that code. In the end, I'd like to run a command with `execa` which itself contains prompts and requires user input. Once that command completes, I'd like to continue with my `Listr2` tasks.

I appreciate your help and if you find some time to look at that, that'd be amazing.

**Comment by mikenikles** [comment]
It's been a while 😄, but I'm back and spend more time on my project.

I tried the new simple renderer to see if it supports my use case. It kind of does, but requires me to hit Enter twice one I'm interacting with the prompts from the CLI I start with `execa`. Also, when I reach the last listr task, the terminal hangs and I have to cancel it with CTRL + C.

If anyone has an idea on how to get this to work, that'd be awesome.

**Comment by cenk1cenk2** [comment]
I do not think I can document this so closing this for archival reasons.
