### ISSUE TITLE
With large list of tasks, huge pause before tasks actually start to be processed

### ISSUE THREAD

**Issue by pbelbin** [cenk1cenk2/listr2#414]
I have a set of perhaps 300 tasks on one `listr` and I'm seeing a huge time delay (say, around 7 minutes) between listing out the initial set of task titles and when the task actions actually start being processed.

Digging around, it appears that by commenting out this line, the huge pause is avoided:

https://github.com/cenk1cenk2/listr2/blob/a4bae730d3056c8f316ef36d440265a148cd9233/src/listr.ts#L125

I see the function is used *prior* to the above line of code too, on a per-Listr basis, and appears to have the job of determining whether the tasks are enabled.  

But, it's not clear to me whether it's *meant* to be doing this not only globally, but *again* before each individual task with what appears to be the same `context` being passed in as argument?  Or, is this `enabled()` function expected to be very fast so that it *can* be called many times?

If this is meant to be a way of making sure that the enabled status is updated as processing proceeds as a way of being dynamic, is there a way to do this without causing the huge delays?  And, of course, there may well be other factors contributing, since I'm converting from Listr to Listr2.  This big delay I'm talking about did not happen with Listr.

Please advise.

**Comment by cenk1cenk2** [comment]
The enable task runs before everything else in a sublist as you expected. Skip works the other way around it would just process the function just before task execution.

Enabled is a empty function if no enabled is given maybe we can ditch that and just mark the task as ready if enabled for a task is not set. That should speed things up. I can not lik to it since I am currently on mobile but i guess that is in lib/task.ts.

Do you use enable by any chance?

**Comment by cenk1cenk2** [comment]
Yeah I realized my stupidity. How it come inside the promise map is a mystery at the moment but that should not be there. I will fix it whenever I have time.

**Comment by pbelbin** [comment]
Thank you for taking care of this! :)
