### ISSUE TITLE
Is it possible to preserve the answers from the prompt?

### ISSUE THREAD

**Issue by xeho91** [cenk1cenk2/listr2#431]
First of all,

thank you very much for the hard work you did with this tool. The developer experience with types and documentation is outstanding, and I love it!

## Question

While hacking, I was trying to figure out if it would be possible to **preserve the answers from the prompts**, as they are displayed in [enquirer](https://github.com/enquirer/enquirer). I would like to have an option where the prompts _(the line with the question and the answer)_ aren't cleared from the console. Is it possible?

## What I tried so far?

I tried enabling the option `options: { preserveOutput: true }` for the task, where the `task.prompt()` is being used, and I was hoping it wouldn't clear which answer(s) I have provided for the prompts. No luck.

Of course, I could just pass the answers to the `task.output = "..."`, but that is a tedious job.

**Comment by cenk1cenk2** [comment]
Hello @xeho91,

This is a bit impossible to achieve with the current configuration due to prompt output is passed through the data channel, marks the task as being a prompt currently, and in the default renderer, it redirects the output of the task, which is the enquirer output while it is a prompt to its own line at the end of all the tasks that get overwritten with each clear ANSI sequence and after the prompt and task finish it clears it to have it ready for the next prompt. It would be very hard to persist that because tons of the output coming from `enquirer` is console clear ANSI sequences and would be hard to say what to keep and what to not.

What I do in this case although not ideal is something like:
```typescript
      // microservice-server types
      {
        skip: (ctx): boolean => !ctx.components.includes(AvailableComponents.MICROSERVICE_SERVER) && !ctx?.microservice,
        task: async (ctx, task): Promise<void> => {
          const choices = mapPromptChoices<AvailableMicroserviceTypes>(AvailableMicroserviceTypes, PrettyNamesForAvailableThingies)

          ctx.microservice = await task.prompt<AvailableMicroserviceTypes>({
            type: 'Select',
            message: 'Please select the microservice server type.',
            choices,
            initial: getInitialFromPriorConfiguration(ctx, 'microservice', choices)
          })

          ctx.injectedCasing.microservice = generateMicroserviceCasing(ctx.name)

          task.title = `Microservice type selected as: ${ctx.microservice}`
        },
        options: {
          bottomBar: Infinity,
          persistentOutput: true
        }
      },

```
