### ISSUE TITLE
Prompt with verbose renderer produces redundant output

### ISSUE THREAD

**Issue by jurijzahn8019** [cenk1cenk2/listr2#435]
Hi,

If using verbose renderer, every input on prompt triggers new message output.

It looks very weird.

![image](https://user-images.githubusercontent.com/44019949/122555937-35408200-d03b-11eb-95cf-6db359b00db7.png)

Is there any possibility to prevent this?

Thanks in advance :)

**Comment by cenk1cenk2** [comment]
hello @jurijzahn8019 ,
sorry for the late reply.

I tried to explain how the prompts work as in here:
https://github.com/cenk1cenk2/listr2/issues/431#issuecomment-856726726

although renderer is different in this case, this verbose renderer is mostly intended for non-tty environments, therefore actually prompts are kind of the second class citizen here. although you can not answer prompts in non-tty environments, since for debugging i am mostly using this verbose renderer, i want to keep it enabled.

so the bottom line is this is not very possible in the current architecture, we have to create another renderer like some kind of simple renderer that will act like a verbose renderer but have some spot for the prompts themselves as in the default renderer. so we again need a refreshing screen to keep the prompt in the bottom of the screen, then it becomes just like the default renderer. here it converts into a kind of endless loop.

**Comment by jurijzahn8019** [comment]
Hi @cenk1cenk2 ,

No real problem here. I just hoped for a quick solution. :) 

I have implemented my own renderer. Which is semi-verbose. I and I struggled to identify whether the output is comming from a prompt. There is a prompt property on the task and it has an untyped property "state" (found via debugger). So for me the quick and reliable solution would be an indication whether the "DATA" is comming from prompt or from "output". In this case I could conditionally use "log-update" or just console.log 

This would really help. 
👍

**Comment by cenk1cenk2** [comment]
Yes, actually that is the same approach you can see here:

https://github.com/cenk1cenk2/listr2/blob/6768e72bcb2de45e6a5afde6e380026d4c96e7b8/src/renderer/default.renderer.ts#L331

If you are so kind and want to share we can add the renderer to the mainstream if it's a simple renderer that streams everything except for the prompts as i imagine it to be and ofc if you want to share that, i guess that would be a good addition. Because that is something I wanted to do but these days I can not just find enough time except for maintenance.

**Comment by cenk1cenk2** [comment]
Thank you for the pull request @jurijzahn8019. I will embed it hopefully this weekend. Thank you so much for your time on this.

Now I really understand the issue with the prompt since you track EOL to keep the last message. Maybe we can do something about it.

As you discussed we can make stdout, stderr selectable but for CI environments maybe it is better to keep it this way.

**Comment by cenk1cenk2** [comment]
Simple renderer is now available, thanks to your effort.

**Comment by jurijzahn8019** [comment]
Great! Thank You!
