### ISSUE TITLE
Update RXJS dependency to version 7.X

### ISSUE THREAD

**Issue by RomainGaillardLesEchos** [cenk1cenk2/listr2#493]
Hi,

We use your npm package in our `monorepo` code base, and we facing the following issue:
 
All others npm packages use `rxjs` up to `7.x` in the code base and your package use `6.6.7` version.

When we make an install of npm packages from root, the wrong version of `rxjs` is installed into root `node_modules` and local `node_modules` are installed inside monorepo packages.

So, it force us to make a `peerDependency` declaration into our root `package.json` to avoid this.

Could you please update your `rxjs` dependency to v 7.x ?

Thx

**Comment by cenk1cenk2** [comment]
Hello @RomainGaillardLesEchos ,

This has been a long-running plague of this repository but I will whole together want to drop rxjs, especially because of its bundle size. With the v4 that has been still in the works and half done in the last couple of months, I converted it in to a more event-emitter-based approach. Because there was also a request before this one that did want me to roll back to rxjs 6.

So I will fill you in with the details whenever this issue progresses. 
You can see my plans here:
https://listr2.kilic.dev/migration/upcoming-changes
