### ISSUE TITLE
Version 3.13.2 and later results in application crash and memory leaks

### ISSUE THREAD

**Issue by Baune8D** [cenk1cenk2/listr2#600]
Reproducible repository here: https://github.com/Baune8D/listr2-clone-failure

`v3.13.5` memory usage spins out of control and the application crashes as more and more tasks fail.
`v3.13.2` no issues with memory usage, but the application gets completely unresponsive as more and more tasks fails.
`v3.13.1` works as it should, no problems here at all.

I guess this is related to cloning introduced in v3.13.2

Included in the example repository is 3 npm scripts:
* `npm run memoryleak` triggers the memory leak issue with version 3.13.5
* `npm run crashes` triggers application crash with version 3.13.2
* `npm run works` runs without problems with version 3.13.1

This has only been tested on `Windows 11` using `Windows Terminal` and `Node.js 16.13.0`

**Comment by cenk1cenk2** [comment]
Hello @Baune8D ,

Thank you so much for this exclusive report. Yes, it makes sense to memory goes crazy for tasks like this because it copies a lot of errors in the memory over and over again with each failure to the error caching mechanism. What I want to do is make the error collection optional. If somebody is not using it should be definitely disabled.

So that would be my plan what do you think about this?

**Comment by cenk1cenk2** [comment]
I do also think that trying to copy circular variables is the cause of the memory leak, so I could just put that in the option because there were people that did want that.

**Comment by Baune8D** [comment]
Sound good to me. Im not really sure what the cloning solves in this case, our application works just fine with v3.13.1, so a switch to revert to something like that behavour would be sufficient for our use case 🙂
