### ISSUE TITLE
Dynamic require of "enquirer" is not supported

### ISSUE THREAD

**Issue by queengooborg** [cenk1cenk2/listr2#631]
In a recent update to `listr2` (or `enquirer`), I had noticed that `task.prompt` would now crash with an error saying that "Enquirer is a peer dependency that must be installed separately."  This error had confused me, however, as I definitely had Enquirer installed.  Instead, I did a bit of debugging to figure out what exactly the underlying error was, and found that there was an error dynamically importing Enquirer.

I have a feeling this might have come from the recent v4 release, where ESM support was added, especially since our project is using ESM.  We're temporarily solving this by calling `enquire.prompt` directly, but this seems to cause some rendering issues, so it's only a temporary fix.

**Comment by cenk1cenk2** [comment]
Hey @queengooborg ,

Thanks for the heads up. If this is a problem with ESM, I will check it in a mock ESM package. I guess I currently only use the `cjs` part of it. 

You can just use the `injectWrapper.enquirer` key to pass it in for now, which should pass your created instance of `enquirer` and pipe it through the renderer. Else as you said it would cause rendering problems since two things are trying to hook up to the stdout to gain control.

**Comment by alopix** [comment]
Just encountered the same issue and can confirm that it seems to be an issue when using ESM (since it worked before, when using CJS). Your suggestion with the listr options `injectWrapper.enquirer` works, thanks.
