### ISSUE TITLE
The title of the task is repeated

### ISSUE THREAD

**Issue by ramsesgarate** [cenk1cenk2/listr2#638]
Hello guys, I hope you are well, the truth is that I don't know much about why this may be happening.

I discovered the library and I wanted to play with it add to a project that I had previously, however, when the task is executed, it starts throwing some numbers and the title of the task continuously until it is finished, how can I solve this?
The terminal I am using is git bash, Strangely in the windows cmd this does not happen to me.

Node version: v16.3.0

Git bash
![image](https://user-images.githubusercontent.com/47763122/156582531-6fd3ec85-0aec-4dd3-9a67-3c3ab95a53d8.png)

CMD
![image](https://user-images.githubusercontent.com/47763122/156583561-a9cf2ae1-003f-4ebc-88b0-c12ed04f937f.png)

**Comment by cenk1cenk2** [comment]
Hey @ramsesgarate ,

To refresh the screen on every render the renderer sends an ANSI control character to delete the line first. This happens around every 100ms so that is why you see it as spam. 

There would be unfortunately no solution to this if the underlying terminal does not implement this feature. 

In non-TTY environments, the renderer will fallback to text-mode but since I suppose git bash advertises as TTY since it has input but does not support the control characters it won't fallback.

So unfortunately I would have no real solution to this except for encouraging you to use something like Windows Terminal with git bash or something.
