### ISSUE TITLE
fix: reset title from null，replace the previous line of output

### ISSUE THREAD

**Issue by monsterboom** [cenk1cenk2/listr2#642]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/listr2/dist/lib/task-wrapper.js b/node_modules/listr2/dist/lib/task-wrapper.js
index 92be7df..548a7d8 100644
--- a/node_modules/listr2/dist/lib/task-wrapper.js
+++ b/node_modules/listr2/dist/lib/task-wrapper.js
@@ -19,6 +19,9 @@ class TaskWrapper {
     }
     /** Change the title of the current task. */
     set title(data) {
+        if (!this.title) {
+          console.log('\n');
+        }
         this.task.title$ = data;
     }
     /** Get the title of the current task. */
```

Scene:
I want to console.log something in the task. I found that when I set task.tittle to null string, console.log can output to terminal. But when I set task.tittle back to a not null value，the function logUpdate will output the this.createRender() and replace the previous line of output.

**Comment by cenk1cenk2** [comment]
Hello @monsterboom,

This is not possible due to unfortunately how that `log-update` is implemented.

This might fix the exact case you are on but it will definitely break others.

The idea was to ditch the `log-update` with `stdout-update` but I have not yet finished it. So `log-update` hooks to the stdout and requires full control to draw on it, since it keeps the data like lines written and lines to be deleted internally. It has no mechanism to hold the data like console.logs until it finishes its job.

So any console.log just messes up the terminal since it loses track of what to keep and what to track.

**Comment by cenk1cenk2** [comment]
I would close this issue since it is not possible to interact with the console while ´log-update´ is running, maybe if we switch to ´stdout-update´ it would solve this since it logs everything out after the render finishes.
