### ISSUE TITLE
Is there a way to return a nonzero exit code if a task fails?

### ISSUE THREAD

**Issue by TonySherman** [cenk1cenk2/listr2#645]
Basically what the title says.

If a task fails, I would like the exit code to be nonzero so it will fail a pipeline build.

Currently if a task fails, the exit code is 0 and in a cicd pipeline, this appears to pass even if the task is necessary to complete.

**Comment by cenk1cenk2** [comment]
Hey @TonySherman,

This can easily be done through JavaScript itself. The Task list `run` command will return a promise and will throw if something bad happens so you can just catch the error and quit manually.

Something like:

```typescript
const listr = new Listr()
try {
  await listr.run()
catch (e) {
  console.error(e)
  process.exit(127)
}
```

**Comment by TonySherman** [comment]
Thanks for the quick response!

**Comment by karlhorky** [comment]
How can this be done with [the `exitOnError: false` option](https://listr2.kilic.dev/task/error-handling.html#methodology:~:text=%5D%2C%0A%20%20%7B-,exitOnError%3A%20false,-%2C%20collectErrors%3A)?

```ts
await new Listr(listrTasks, {
  exitOnError: false,
}).run();
```

Maybe I need to [assign to `tasks` and then check for `tasks.errors`](https://listr2.kilic.dev/task/error-handling.html#methodology:~:text=Since%20exitOnError%20is%20false%20on%20that%20context%2C%20ListrError%20will%20get%20collected%20by%20tasks.errors%5D%2C%20and%20the%20value%20will%20be%20%7B%20message%3A%20%271%27%2C%20type%3A%20ListrErrorTypes.HAS_FAILED_WITHOUT_ERROR%20%7D)?

```ts
const tasks = await new Listr(listrTasks, {
  exitOnError: false,
});

await tasks.run();

if (tasks.errors.length > 0) {
  process.exit(1);
}
```

**Comment by karlhorky** [comment]
Ahh I guess I need specify both `exitOnError: false` and `collectErrors: 'minimal' | 'full'`, this seems to work:

```ts
const tasks = await new Listr(listrTasks, {
  exitOnError: false,
  collectErrors: 'minimal',
});

await tasks.run();

// Exit the process with exit code 1 when errors encountered
if (tasks.errors.length > 0) {
  process.exit(1);
}
```

**Comment by cenk1cenk2** [comment]
Hey Karl,

You can enable [colected-errors](https://listr2.kilic.dev/task/error-handling.html#collected-errors) for having that functionality than `tasks.errors` would be populated. Since it was an under utilized feature with the latest major version I just disabled it and made it opt-in.

**Comment by cenk1cenk2** [comment]
ah you beat me to it :D
