### ISSUE TITLE
Enquirer prompt name value and passing custom instance to children

### ISSUE THREAD

**Issue by Josh-Walker-GM** [cenk1cenk2/listr2#657]
**Confirm correct usage**
I have been trying to use a custom instance of `enquirer` for testing needs. I think I have now understood this needs to be given via a
```js
injectWrapper: { enquirer: customEnquirer }
```
rather than a
```js
rendererOptions: { enquirer: customEnquirer }
```
but it would be great if you could confirm this? I have confirmed this works for me by adding a listener to `customEnquirer.on('prompt', ...)` and seeing that it fires for the first case but not the second.

I did find it somewhat difficult to come to this finding. Perhaps I missed some docs or they miss this point?

**Prompt name option value**
In the testing I wish to check what the name associated with the current prompt event is. I should be able to do this via the `prompt.name` field. However the prompt event only contains the value `default` as the `prompt.name` regardless of when I set it via code like:
```js
const response = await task.prompt({
  type: 'confirm',
  name: 'NOT_DEFAULT',
  message: `Do you want to do something?`,
  default: false,
})
```
Can you confirm this property isn't being forwarded down or help with my understanding of why I am seeing only `default`?

**The custom enquirer instance being propagated to children**
I appear to need to manually give all subtasks the `injectWrapper: { enquirer: customEnquirer },` option. Should this be considered an option which can propagate to subtasks from the parent?

Apologies if this issue is too bloated with the 3 sub-issues I've raised 😅

**Comment by cenk1cenk2** [comment]
Hey sorry I am on the phone but as a quick reply I suppose this would be better than to keep you waiting.

injectWrapper part is correct since enquirer can be used with any of the renderers and it injects itself to the task wrapper. I suppose there is no clear documentation on this but I am trying to write a new documentation website for listr but could not find any time lately.

The default thing comes from my design decision which is if you have only one prompt it names it default so you do not have to do await (prompt()).default everytime. But multiple prompts as in the case you pass an array there should have their names and act more like enquirer.

For the third one I do not think enquirer propagates to subtasks properly but I am not really sure. That is poor design and should be fixed.

**Comment by Josh-Walker-GM** [comment]
Thanks so much for the quick reply, very much appreciated! 

Okay, thanks for confirming where my thoughts are correct and incorrect. I should be able to work around that design decision of the `name` field by using the default value field instead (`default`). The propagation to the children is only really for neatness of the code so it's not a blocker or anything for me.

**Comment by cenk1cenk2** [comment]
All cool then have a nice day @Josh-Walker-GM. You can append to this issue if you find any limitations. There should be some tests for enquirer in the project tests folder.
