### ISSUE TITLE
Testing prompts

### ISSUE THREAD

**Issue by innocenzi** [cenk1cenk2/listr2#66]
Hello. 

I am trying since a while to determine how I am supposed to create tests for the prompts. Using `Enquirer` directly, I can use its events, but using `Listr`, I don't have access to the underlying `Enquirer` object. 

Is there currently any way to test prompts? Thanks!

**EDIT** - I think the ability to pass an instance of `Enquirer`, the same as `logger`, to a `Listr` object, would solve the issue, because we would be able to pass a fake `Enquirer` object, hence, to test it.

**Comment by cenk1cenk2** [comment]
Hi Mr. Innocenzi,

I think that idea is feasible and doable. I will have a look at that this weekend because at last, I was also planning to add tests for renderers. I was planning to that with [jest-mock-process](https://github.com/EpicEric/jest-mock-process). Maybe that can be the answer since you can manipulate stdout as well as stdin. But you are right, unfortunately, at the moment there is no easy way to spy on the instance of enquirer since I converted it to be a dynamic import.

**Comment by innocenzi** [comment]
Hi, thank you for your answer! I look forward to a change in that direction. Let me know if I can be of any help.

**Comment by cenk1cenk2** [comment]
Can you try the latest beta from `listr2@beta`. I was also writing something basing this as a dependency had to do some minor fixes, so hopefully added your functionality before weekend as well, weeee.

**Comment by innocenzi** [comment]
You went fast! And it looks good, I'll take a look tomorrow. Thank you!
