### ISSUE TITLE
Syntax Error on Nullish coalescing operator even when using with Node v16.17.1

### ISSUE THREAD

**Issue by Raneet10** [cenk1cenk2/listr2#661]
Hey folks!

We're faced with this issue when using Listr2 `5.0.6` with node `v16.17.1` : 

```
/home/ubuntu/matic-cli/node_modules/listr2/dist/index.cjs:90
    this.path = [...task.listr.path ?? [], task.title].join(" > ");
                                                      ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
```

This apparently seems to be due to the `nullish coalescing operator (??)` which should be supported given the node version we're using : https://node.green/

Downgrading Listr2 to an older `4.x.x` version seems to work fine but we'd obviously prefer to use the latest release. Anything that I could be missing here or suggestions to mitigate this error ? 

Thanks!

**Comment by cenk1cenk2** [comment]
Hello @Raneet10 ,

There should be something wrong with your environment where you might not be using node 16 for the project somehow, this can happen if you have the wrong configuration for node version managers on a certain shell. Please verify this, because this does not seem like something that I can fix.

Sorry for the inconvenience, hope you can find the solution.
